name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Run workflow on push to main
  pull_request:
    branches:
      - main  # Run workflow on pull request to main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows GitHub Actions to push changes to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetches all history for proper deployment

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Change to the correct output directory if necessary
          destination_branch: gh-pages  # Ensures deployment goes to the correct branch
